#AutoGenerator 
#普通配置 
onlyCreateTemplates: !!str false
#tablePrefix: cy_
#项目名
project.name: online-order-web
#-- 俩id挂了、generator之前做个备份、saveOrUpdateByCheck方法bug:检测没有记录无法插入id、增加一个条件更新
OutputDir: D:/Project/*{project.name}/src/main/java
#配置文件路径
OutputDirConfig: D:/Project/*{project.name}/src/main/resources/
#静态资源路径 
OutputDirStatic: D:/Project/*{project.name}/src/main/resources/static
#静态资源路径 
OutputDirJars: D:/Project/*{project.name}/src/main/resources/jars
#templatesDir D:/Project/*{project.name}/src/main/resources/views
OutputDirTemplates: D:/Project/*{project.name}/src/main/resources/views/
#templatesPath
templatesPath: classes/templates
#作者名
author: linking
#controller uri前缀 
prefix.ctrl: /
#html访问 uri前缀
prefix.view: /view/
#基础包名  
basePackage: com.huihaha.onlineorder
#登录表名
login.table: user
login.usercolumn: username
login.pwdcolumn: password
#需要逆向的表(不写默认是全部表)
tables: authority,my_authority
#是否初始化（生成拷贝文件）只生成baseclass、xml、和各层的文件
createWebtemplates: !!str true
createConfig: !!str false
createStatic: !!str false
createJars: !!str false
createAnalyze: !!str false
createGeneratorConfig: !!str false
createBaseclass: |- 
  *{!onlyCreateTemplates}
createEntity: |- 
  *{!onlyCreateTemplates}
createXml: |- 
  *{!onlyCreateTemplates}
#是否覆盖文件（（xml）和entity、mapper或其他拷贝文件除外）
isOverFile: !!str false

#jdbc配置
jdbc.driver: com.mysql.cj.jdbc.Driver
jdbc.url: jdbc:mysql://app.j66c.com:3306/huihaha?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
jdbc.user: root
jdbc.pwd: lang1987
#5.0的时候会更改配置
mysql.version: !!str 5.0
#各层包名配置
package.suffix.mapper: dao
package.suffix.entity: entity
package.suffix.service: service
package.suffix.serviceImpl: service.impl
package.suffix.controller: controller
package.suffix.xml: mapper

#数组默认生成的是ArrayList
#使用说明
# 使用方法一开始为一个数组，第一层为所需要连接的表（为主表），第二层是要连接的表，可以是多个，第三层是第二层要连接的表
#conj.infor: 
#  - 
#    table: orders #表名
#    relation: one #连接关系，第一层可以不写（one or many）
#    condition: orders.id = order_id and goods.id = goods_id #新版本改成每一层条件分离，第一层的是额外条件
#    innertables:  #要连接的表，可以是多个
#      - 
#        table: orderitem #要连接的表名
#        relation: many #指定连接的类型
#        conjtype: inner #连接类型，可以是left或inner，不写默认是inner（新版本conjtype代表前表以什么方式连接此表）
#        innertables: 
#          - 
#            table: goods
#            relation: one
#  - #第二个连接表
#    table: classify
#    condition: classify.id = classify_id #在左连接的时候条件也是要有顺序的
#    conjtype: left
#    innertables: 
#      - 
#        table: goods
#        relation: many
## 使用方法一开始为一个数组，第一层为所需要连接的表（为主表），第二层是要连接的表，可以是多个，第三层是第二层要连接的表
conj.infor: 
  - 
    table: find
    innertables: #mybatis结果集是有顺序的，一对一的必须要写在前边
      - 
        table: img
        condition: find.find_id = img.use_id
        relation: many
        conjtype: left
  - 
    table: lose
    innertables: #mybatis结果集是有顺序的，一对一的必须要写在前边
      - 
        table: img
        condition: lose.lose_id = img.use_id
        relation: many
        conjtype: left
#一个表可能有多个模板，所以这里面有多少个就要建多少个FileOutput
webtemplates: 
  - 
    tables: [authority,my_authority]
    template: list.html
    icons: ["fa fa-calendar-plus-o","fa fa-user","fa fa-bandcamp","",""]
    outpath: ${entity}/list.html
    exclude: all.bz1,all.bz2
  - 
    tables: [authority,my_authority]
    template: add.html
    outpath: ${entity}/add.html
    exclude: all.bz1,all.bz2
  - 
    tables: [authority,my_authority]
    template: edit.html
    outpath: ${entity}/edit.html
    exclude: all.bz1,all.bz2
  - 
    tables: [authority,my_authority]
    template: edit_vertical.html
    outpath: ${entity}/edit_vertical.html
    exclude: all.bz1,all.bz2
#指定文件类型（表名重复时不识别,加时间下划线自动创建）:{0:女,1:男}、img、sex、file、(date、datetime-加_自动创建时间）、（_uuid、_dateNo、_squNo,包含双下滑先表示不可见不可加，一个下划线可见不可加）
propertyType: 
#  uriPrefix:key:name:firstId(用于判断是否使用函数):secondId(用于判断初始化和change触发名)
  find: 
    find_id: uuid
  lose: 
    lose_id: uuid
  img:
    url: img