#AutoGenerator 
#普通配置 
onlyCreateTemplates: !!str false
#tablePrefix: hhh_
useMyBatitsPlus: !!str false
#项目名
project.name: test
#项目根目录
OutputDirRoot: D:/Project/*{project.name}/
#-- 俩id挂了、generator之前做个备份、saveOrUpdateByCheck方法bug:检测没有记录无法插入id、增加一个条件更新
OutputDir: D:/Project/*{project.name}/src/main/java
#配置文件路径
OutputDirConfig: D:/Project/*{project.name}/src/main/resources/
#静态资源路径 
OutputDirStatic: D:/Project/*{project.name}/src/main/resources/static
#静态资源路径 
OutputDirJars: D:/Project/*{project.name}/lib
#templatesDir D:/Project/*{project.name}/src/main/resources/views
OutputDirTemplates: D:/Project/*{project.name}/src/main/resources/views/
#templatesPath
templatesPath: classes/templates
#作者名
author: Jack
#controller uri前缀 
prefix.ctrl: /
#html访问 uri前缀
prefix.view: /view/teacher/
#基础包名  
basePackage: com.colin.teaching_aid_sys
#登录表名
login.table: admin
login.usercolumn: username
login.pwdcolumn: password
#需要逆向的表(不写默认是全部表)
tables: 
#是否初始化（生成拷贝文件）只生成baseclass、xml、和各层的文件
createWebtemplates: !!str true
createRoot: !!str true
createConfig: !!str true
createStatic: !!str true
createJars: !!str true
createAnalyze: !!str false
createGeneratorConfig: !!str false
createBaseclass: |- 
  *{!onlyCreateTemplates}
createEntity: |- 
  *{!onlyCreateTemplates}
createXml: |- 
  *{!onlyCreateTemplates}
#是否覆盖文件（（xml）和entity、mapper或其他拷贝文件除外）
isOverFile: !!str false

#jdbc配置
jdbc.driver: com.mysql.cj.jdbc.Driver
jdbc.url: jdbc:mysql://localhost:3306/teaching_aid_sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
jdbc.user: root
jdbc.pwd: root
#5.0的时候会更改配置
mysql.version: !!str 5.0
#各层包名配置
package.suffix.mapper: dao
package.suffix.entity: entity
package.suffix.service: service
package.suffix.serviceImpl: service.impl
package.suffix.controller: controller
package.suffix.xml: mapper

#数组默认生成的是ArrayList
#使用说明
# 使用方法一开始为一个数组，第一层为所需要连接的表（为主表），第二层是要连接的表，可以是多个，第三层是第二层要连接的表
#conj.infor: 
#  - 
#    table: orders #表名
#    relation: one #连接关系，第一层可以不写（one or many）
#    condition: orders.id = order_id and goods.id = goods_id #新版本改成每一层条件分离，第一层的是额外条件
#    innertables:  #要连接的表，可以是多个
#      - 
#        table: orderitem #要连接的表名
#        relation: many #指定连接的类型
#        conjtype: inner #连接类型，可以是left或inner，不写默认是inner（新版本conjtype代表前表以什么方式连接此表）
#        innertables: 
#          - 
#            table: goods
#            relation: one
#  - #第二个连接表
#    table: classify
#    condition: classify.id = classify_id #在左连接的时候条件也是要有顺序的
#    conjtype: left
#    innertables: 
#      - 
#        table: goods
#        relation: many
## 使用方法一开始为一个数组，第一层为所需要连接的表（为主表），第二层是要连接的表，可以是多个，第三层是第二层要连接的表
conj.infor: 
  - 
    table: course
    innertables: #mybatis结果集是有顺序的，一对一的必须要写在前边
      - 
        table: teacher
        condition: course.teach_id = teacher.teach_id
        relation: one
        conjtype: inner
  - 
    table: student_work
    innertables: 
      - 
        table: work
        condition: student_work.work_id = work.work_id
        relation: one
        conjtype: inner
  - 
    table: student_course
    innertables: 
      - 
        table: course
        condition: student_course.course_id = course.course_id
        relation: one
        conjtype: inner
  - 
    table: clazz
    innertables: 
      - 
        table: student
        condition: clazz.class_id = student.class_id
        relation: many
        conjtype: left
  -
    table: clazz
    innertables: 
      - 
        table: clazz_course
        condition: clazz.class_id = clazz_course.class_id
        relation: many
        conjtype: left
#一个表可能有多个模板，所以这里面有多少个就要建多少个FileOutput
webtemplates: 
  - 
    tables: [admin,course,student,student_work,teacher,work,student_course,clazz_course,announcement]
    template: java_v1/add.html
    outpath: teacher/${entity}/add.html
    exclude: all.bz1,all.bz2
  - 
    tables: [admin,course,student,student_work,teacher,work,student_course,clazz_course,announcement]
    template: java_v1/edit.html
    outpath: teacher/${entity}/edit.html
    exclude: all.bz1,all.bz2
  - 
    tables: [clazz]
    template: java_v1/add_vertical.html
    outpath: teacher/${entity}/add.html
    exclude: all.bz1,all.bz2
  - 
    tables: [clazz]
    template: java_v1/edit_vertical.html
    outpath: teacher/${entity}/edit.html
    exclude: all.bz1,all.bz2
  - 
    tables: [admin,course,student,student_work,teacher,work,student_course,clazz,clazz_course,announcement]
    template: java_v2/list.html
    icons: [layui-icon-username,layui-icon-release,layui-icon-user,layui-icon-read,layui-icon-group,layui-icon-list,layui-icon-list,layui-icon-list]
    outpath: teacher/${entity}/list.html
    exclude: all.bz1,all.bz2
  -
    tables: [admin]
    template: java_v1/include.html
    outpath: include.html
    exclude: all.bz1,all.bz2
  -
    tables: [admin]
    template: java_v2/index.html
    outpath: index.html
    exclude: all.bz1,all.bz2
  -
    tables: [admin]
    template: java_v2/login.html
    outpath: login.html
    exclude: all.bz1,all.bz2
  
#指定文件类型（表名重复时不识别,加时间下划线自动创建）:{0:女,1:男}、img、sex、file、(date、datetime-加_自动创建时间）、（_uuid、_dateNo、_squNo,包含双下滑先表示不可见不可加，一个下划线可见不可加）
propertyType: 
#  uriPrefix:key:name:firstId(用于判断是否使用函数):secondId(用于判断初始化和change触发名)
  student_work: 
    app_time: _datetime
    pass_time: _datetime
    stu_id: student:stuId:name
    work_id: work:workId:name
  student:
    stu_id: _dateNo
    class_id: clazz:classId:name
    major: |-
       {"0":"计算机与科学技术","1":"经济学","2":"哲学","3":"教育学"}
  teacher: 
    teach_id: _dateNo
    depart: |-
       {"0":"土木工程系","1":"心理学系","2":"数学科学学院","3":"物理学院"}
  course: 
    teach_id: teacher:teachId:name
    type: |-
       {"0": "选修课", "1": "必修课"}
  clazz_course: 
    class_id: clazz:classId:name
    course_id: course:courseId:name
  work: 
    course_id: course:courseId:name
    type: __out
  announcement: 
    teach_id: teacher:teachId:name
    class_id: clazz:classId:name
    create_time: _datetime