#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: ${package.Entity}
  mapperLocations: classpath:${cfg.packageSuffixXml.replace(".","/")}/*.xml
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
logging: 
  level: 
    ${package.Mapper}: debug
#开发配置
spring:
  profiles: dev
  datasource:
    url: ${cfg.jdbcUrl}
    username: ${cfg.jdbcUser}
    password: ${cfg.jdbcPwd}
    driver-class-name: ${cfg.jdbcDriver}
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
