#AutoGenerator
#普通配置
OutputDir: ${cfg.OutputDir}
#配置文件路径
OutputDirConfig: ${cfg.OutputDirConfig}
#webroot路径
OutputDirWeb: ${cfg.OutputDirWeb}
#作者名
author: ${cfg.author}
#基础包名
basePackage: ${cfg.basePackage}
#登录表名
login.table: 
login.usercolumn: username
login.pwdcolumn: password
#conjunctive
#conj.infor: [{"tables":  "order_form,orderitem,room", "condition": "and "}]
#需要逆向的表(不写默认是全部表)
tables: $!{cfg.tables}
#是否初始化（生成拷贝文件）
isInit: !!str false
#是否覆盖文件（xml和entity或其他拷贝文件除外）
isOverFile: !!str false

#jdbc配置
jdbc.driver: ${cfg.jdbcDriver}
jdbc.url: ${cfg.jdbcUrl}
jdbc.user: ${cfg.jdbcUser}
jdbc.pwd: ${cfg.jdbcPwd}

mysql.version: !!str ${cfg.mysqlVersion}

#数组默认生成的是ArrayList
conj.infor: 
  - 
    table: orders
    relation: one
    innertables: 
      - 
        table: orderitem
        relation: many
        innertables: 
          - 
            table: goods
            relation: one
    #不写默认是null
    condition: orders.id = orderitem.order_id and orderitem.goods_id = goods.id
    #内连接 inner、左连接 left ，不写默认inner
    conjtype: inner